<div style="position:relative">
    <div id="search_autocomplete" class="search-autocomplete" style="position: absolute;width: 250px;">
        <ul role="listbox">
             <script id="search-template" type="text/x-magento-template">
                 <li>
                     Name : <%- data.name %>
                 </li>
                 <li>
                     Sku : <%- data.salary %>
                 </li>
            </script>
        </ul>
    </div>
</div>